---
name: Run Daily Provisioning Test Suites
description: "Runs daily provisioning test suites"

inputs:
  reporting:
    description: "Enable reporting"
    required: false
    default: "false"
  tags:
    description: "Test tags to run (comma-separated)"
    required: false
    default: "recurring"

runs:
  using: composite
  steps:
    - name: Run Provisioning Tests
      id: provisioning
      shell: bash
      continue-on-error: true
      run: |
        set +e

        gotestsum --format standard-verbose \
          --packages=github.com/rancher/tests/validation/provisioning/... \
          --junitfile results_provisioning.xml \
          --jsonfile results_provisioning.json \
          -- -timeout=3h -tags=${{ inputs.tags }} -v

        provisioning_exit=$?
        echo "provisioning_exit=$provisioning_exit" >> "$GITHUB_ENV"

        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi

    - name: Show failed tests
      run: |
        failed=0
        if [ "$provisioning_exit" -ne 0 ]; then
          echo "Failed Provisioning tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results_provisioning.json
          failed=1
        fi

        if [ "$failed" -eq 1 ]; then
          exit 1
        fi
      shell: bash
